In [1]:
import torch
import numpy as np
import time
import torch.nn.functional as F
device = 'model_display' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
import torch.nn as nn

In [3]:
start_time = time.time()

# matrix operation 
zeros = torch.zeros(1, 1)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .4f}")

 0.0146


In [4]:
### why we use gpu rather than cpu for training efficiency ?
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

np_rand1 = np.random.randint(0, 100, size = (10000, 10000))
np_rand2 = np.random.randint(0, 100, size = (10000, 10000))


start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .4f}")

###############################

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .4f}")


 13.5260
 5.8459


In [5]:
# define a probability in tensore
probabilities = torch.tensor([0.1, 0.9]) # index 0 : 10% probability for 0, index 1: 90% probability for 1

## draw 5 samples from a multinomial distributions
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [6]:
## concatination
tensor = torch.tensor([1, 2, 3, 4]) # <- first tensor and second tensor is : torch.tensor([5]) 
out = torch.cat((tensor, torch.tensor([5])), dim = 0) # list of number will be concatinated with 5 row wise (dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [7]:
out = torch.tril(torch.ones(5, 5)) # triangle lower -> tril , triangle upper -> triu
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf')) ## fil lower triangle with 0 and upper tri with infinity
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [10]:
## exponentiate
torch.exp(out) ## anything exponentiate with 0 become 1, and exponentiate with -inf become 0
## for example:
## 2.71 exponent 0 = 1
## 2.71 exponent 1 = 2.71
## 2.71 exponent -inf = 0

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
input = torch.zeros(2, 3, 4) ## 3 dim -- 2 matrix with 3 x 4 (3 rows, 4 columns)
out = input.transpose(0, 2) ## (4 x 3 x 2) swap 0th position to 2nd position -- means 4 will swap with 2 (2, 3, 4) ---> (4, 3, 2)
out.shape

torch.Size([4, 3, 2])

In [12]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# stacked the tensor along the new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
##layers
#import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias = False)
print(linear(sample))

tensor([2.4345, 1.8335, 6.9860], grad_fn=<SqueezeBackward4>)


In [14]:


tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim = 0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [15]:
## embedding -- text as vector


# Define the size of the vocabulary and the dimensionality of the embeddings
vocab_size = 1000  # Example: 10,000 unique words
embedding_dim = 100  # Example: 100-dimensional embeddings -- each word will represent by a vector of length 100

# Create an instance of the Embedding module
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Generate some example input indices
input_indices = torch.tensor([1, 5, 3, 7, 2]) ## ech index refers to an unique word

# Pass the input indices through the embedding layer
embedded_vectors = embedding_layer(input_indices)

print(embedded_vectors)
print(embedded_vectors.shape)  # Output shape: (5, 100) - 5 input indices, each mapped to a 100-dimensional vector


tensor([[-0.3268, -0.5199,  0.7009, -0.3301, -0.5987,  0.7230, -1.6430, -0.0057,
         -0.2579,  1.1300,  0.1810,  0.8028,  1.3026,  1.2550, -0.2810,  1.4226,
          0.1118,  0.1925,  0.5715, -0.6957, -0.1223, -0.9529,  0.1449, -0.2712,
         -0.7013,  1.2513,  0.8363,  0.3756,  0.7024,  0.5907,  0.1469,  0.9032,
          0.7739,  0.4144,  0.2610,  0.0884,  1.5544,  0.8369,  0.6022, -0.2287,
         -0.5456, -0.7468,  1.3985, -0.7245,  0.2093, -1.1007, -0.0991, -0.8317,
          0.0973, -0.9202,  0.7358, -1.5782, -1.0972, -1.3005, -1.3843, -2.3146,
         -0.0906, -0.0806, -1.9762, -0.3751, -1.6567, -0.2554,  0.7431,  2.0005,
         -0.6032, -1.9462, -0.8349, -0.9369,  0.9286, -0.3820, -0.9311, -0.3032,
          0.5282, -0.2616, -1.6293, -2.1495, -0.0468,  2.7165, -0.8450, -0.2240,
         -1.2859,  1.2833,  2.1363,  1.5365, -0.1238, -2.0153,  0.0540,  0.5643,
          0.5027,  0.5764, -0.5486, -0.6484,  1.2491,  0.8258,  0.4525,  0.0293,
          0.0500,  0.0572,  

In [16]:
### dot product
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [17]:
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [18]:
##int_64 = torch.randint(1, (3, 2)) ## --- ERROR
# after casting
int_64 = torch.randint(1, (3, 2)).float() ## from 0 to 1, 3 x 2 matrix
float_32 = torch.rand(2, 3)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [19]:
int_64

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape ## unpack with .shape
a = a.view(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])


In [21]:
print(a.view(x, y, z))

tensor([[[0.1834, 0.1469, 0.2492, 0.9437, 0.7061],
         [0.6374, 0.1335, 0.6950, 0.1056, 0.4235],
         [0.3272, 0.9686, 0.7431, 0.1919, 0.7415]],

        [[0.2400, 0.7935, 0.2158, 0.0239, 0.1154],
         [0.0327, 0.8077, 0.9246, 0.2716, 0.3800],
         [0.6198, 0.8862, 0.6403, 0.3932, 0.7205]]])


In [22]:
x = torch.rand(2, 3, 5)
print(x)

tensor([[[0.2412, 0.8255, 0.7798, 0.2267, 0.6787],
         [0.7072, 0.1479, 0.7315, 0.9378, 0.3703],
         [0.7473, 0.5145, 0.1620, 0.7435, 0.9063]],

        [[0.0099, 0.6239, 0.5919, 0.4210, 0.8733],
         [0.5091, 0.5602, 0.4252, 0.2979, 0.3006],
         [0.2915, 0.3054, 0.3460, 0.2391, 0.5263]]])


In [23]:
torch.zeros(1,1)

tensor([[0.]])

In [3]:
## activation function
x = torch.tensor([-0.05, 0.1, -0.2], dtype = torch.float32)
y = F.relu(x)
print(y) ## negative values are replaced with zero

tensor([0.0000, 0.1000, 0.0000])


In [4]:
x = torch.tensor([-0.05, 0.001, -0.2], dtype = torch.float32)
y = F.sigmoid(x) ## 1/1+exp(−x)
print(y)

tensor([0.4875, 0.5002, 0.4502])


In [5]:
x = torch.tensor([-0.05, 0.001, -0.2], dtype = torch.float32)
y = F.tanh(x) ## exp(x)−exp(−x)/exp(x)−exp(−x)
print(y)

tensor([-0.0500,  0.0010, -0.1974])
